version: "3.9"

services:
  api:
    build: .
    image: ztueduua-ldap-via-http:latest
    container_name: ldap-http-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/healthz"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 10s
